language: node_js
node_js:
- '10'
- '12'
after_success: yarn run coverage
notifications:
  slack:
    secure: aHIGPJ4SiLqhoqyhGlvjjRGQtsM3S71za7SRvcM8L5Dede5topaoi/VHS2opyLjc4xvk/9cfgFtGsjefU19JgNSaKzYjs2QYSILWbiYszQUxc3917REEHzLJ1/XXhbFstOquOaQzFBD34/XdV3tqhCXJYonZewFOb8WEdFKZgs3pin+VqDPMrez6rAcnrEzuHDpPEEVGkPOXNdrEsuat/6Z+9RNDxKz5lu8qJNfJRg4tHxSm3kt54Qi569Pkg9CMNRwS5i6laNrv0q0mo+/opjZknpclBrW/i5j1SCepoywfn5lbSY8TU5h2ptwZU2yUKPaTOxaI5t6Bn0OUPBGBavbdyhEBKd5gMLDn8XIZln8LPzdp1Saab7z5knGkGkr298sz6QVqLvOUMVQsaSzpdACKD1jhxd1WDRZuzuyuFN0K1FGtaG8oTMUaisxtxvZH8iNCC09noLNCP9RodC4WNUJXEbL2ykzlweMaf6uhGTpYVEd3mjdd5o3wQMVnk1FwjK3Kq9ZK814VY6S3m+8fju7i12f3TnXT+4T4ZFy9VjnssgdJctFT7TJmUrP7ldDq1hWCsgsEcTJQhLRPiQt1QUqFcv5m2aRLWoFuMzlRcLpYSTrf2Ik1AClfQY2pi7NYGHrRsMIRwRO6Fii6eANvq1ZxUiyZtwc+fcesm8fDgsM=
